## R script to run a differential expression analysis
## using DESeq2.
## Counts files must be generated by HTSeq.
## Ramón Peiró-Pastor & Eva Castillo Rosa (CBMSO 2015)
## Based on a draft script by Alberto Rastrojo Lastras (CBMSO)
##################################################################

## O. Clean and libraries
##################

cat("\n Checking if all libraries are installed \n")
rm(list=ls())

if ("optparse" %in% row.names(installed.packages())  == FALSE) install.packages("optparse")
if ("vsn" %in% row.names(installed.packages())  == FALSE) BiocManager::install("vsn")
if ("gplots" %in% row.names(installed.packages())  == FALSE) install.packages("gplots")
if ("ggplot2" %in% row.names(installed.packages())  == FALSE) install.packages("ggplot2")
if ("RColorBrewer" %in% row.names(installed.packages())  == FALSE) install.packages("RColorBrewer")
if ("cluster" %in% row.names(installed.packages())  == FALSE) install.packages("cluster")
if ("pheatmap" %in% row.names(installed.packages())  == FALSE) install.packages("pheatmap")
if ("grid" %in% row.names(installed.packages())  == FALSE) install.packages("grid")
if ("manhattanly" %in% row.names(installed.packages())  == FALSE) install.packages("manhattanly")
if ("htmlwidgets" %in% row.names(installed.packages())  == FALSE) install.packages("htmlwidgets")
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
if ("DESeq2" %in% row.names(installed.packages()) == FALSE) BiocManager::install("DESeq2")
if ("AnnotationDbi" %in% row.names(installed.packages()) == FALSE) BiocManager::install("AnnotationDbi")
if ("scales" %in% row.names(installed.packages())  == FALSE) install.packages("scales")

suppressPackageStartupMessages({
  library(optparse, quietly = TRUE)
  library(vsn, quietly = TRUE)
  library(gplots, quietly = TRUE)
  library(ggplot2, quietly = TRUE)
  library(RColorBrewer, quietly = TRUE)
  library(cluster, quietly = TRUE)
  library(pheatmap, quietly = TRUE)
  library(grid, quietly = TRUE)
  library(manhattanly, quietly = TRUE)
  library(htmlwidgets, quietly = TRUE)
  library(BiocManager, quietly = TRUE)
  library(DESeq2, quietly = TRUE)
  library(AnnotationDbi, quietly = TRUE)
  library(scales)
})


## 1. Parse arguments
#####################


option_list = list(
  make_option(c("-c", "--configfile"), type="character", default=NULL, 
              help="configuration file must have the next structure: 'sample' 'file' 'condition' (tab-separated and with that header)", metavar="character"),
  make_option(c("-p", "--cutoff"), type="numeric", default=0.05, 
              help="cut-off value to assign DEGs", metavar="numeric"),
  make_option(c("-d", "--database"), type="character", default=NULL, 
              help="the name of the annotation database in the format org.XX.eg.db (to add gene names)", metavar="character")
)

opt_parser = OptionParser(option_list=option_list)
opt = parse_args(opt_parser)

if (is.null(opt$configfile)){
  print_help(opt_parser)
  stop("AT LEAST ONE ARGUMENT MUST BE PROVIDED", call.=FALSE)
}


## 2. Parameters
################

# load configuration file
config <- opt$configfile
sampleTable <- read.table(config, header=TRUE)

cutoff <- opt$cutoff

orgdb <- opt$database

if (!is.null(orgdb)){
    if (orgdb %in% row.names(installed.packages()) == FALSE) BiocManager::install(orgdb)
        suppressPackageStartupMessages({
        library(orgdb, quietly = TRUE, character.only = TRUE)
    })
}

## 3. Read data
###############

data <- DESeqDataSetFromHTSeqCount(sampleTable, directory=".", design= ~condition)
# extract unique elements of condition
levels <- unique(sampleTable$condition)
ll <- length(levels)

## 4. Differential test
#######################

# Analysis
#---------

dds <- DESeq(data)
ncounts <- counts(dds, normalized=TRUE)
write.table (ncounts, file="deseq2_counts.tsv", quote=FALSE, sep = "\t", col.names=NA)

# Data transformations to better visualize them
#----------------------------------------------

# Tikhonov Regularized Log Transformation (RLT)
# see http://en.wikipedia.org/wiki/Tikhonov_regularization
rlt <- rlog(dds)
rltMat <- assay(rlt)
# variance stabilizing transformation (VST)
# see http://en.wikipedia.org/wiki/Variance-stabilizing_transformation
vst <- varianceStabilizingTransformation(dds)
vstMat <- assay(vst)
# effects of the transformation in the variance
notAllZero <- (rowSums(counts(dds))>0)	# dicard zero counts

tiff(filename = "deseq2_log2counts.tiff", units="in", width=5, height=5, res=300)
msd <- meanSdPlot(log2(ncounts[notAllZero,] + 1))
msd$gg + ggtitle("Log2+1 raw counts")
invisible(dev.off())

tiff(filename = "deseq2_rlt.tiff", units="in", width=5, height=5, res=300)
msd <-  meanSdPlot(rltMat[notAllZero,])
msd$gg + ggtitle("Regularized Log Transformation (RLT)")
invisible(dev.off())

tiff(filename = "deseq2_vst.tiff", units="in", width=5, height=5, res=300)
msd <- meanSdPlot(vstMat[notAllZero,])
msd$gg + ggtitle("Variance Stabilizing Transformation (VST)")
invisible(dev.off())

# Data quality assesment
#-----------------------

select <- order(rowMeans(counts(dds,normalized=TRUE)),decreasing=TRUE)[1:30]
hmcol <- colorRampPalette(c("yellow", "black", "cyan"))(299)

tiff(filename = "deseq2_hm30_raw.tiff", units="in", width=5, height=5, res=300)
par(cex.main=0.8)
heatmap.2(ncounts[select,], col=hmcol, Rowv=FALSE, Colv=FALSE, scale="none",
	dendrogram="none", trace="none", margin=c(5, 7), main="30 most highly \n expressed genes (Raw counts)", labRow=F, key.title=NA)
invisible(dev.off())
	
tiff(filename = "deseq2_hm30_rlt.tiff", units="in", width=5, height=5, res=300)
par(cex.main=0.8)
heatmap.2(rltMat[select,], col=hmcol, Rowv=FALSE, Colv=FALSE, scale="none",
	dendrogram="none", trace="none", margin=c(5, 7), main="30 most highly \n expressed genes (RLT)", labRow=F, key.title=NA)
invisible(dev.off())

tiff(filename = "deseq2_hm30_vst.tiff", units="in", width=5, height=5, res=300)
par(cex.main=0.8)
heatmap.2(vstMat[select,], col=hmcol, Rowv=FALSE, Colv=FALSE, scale="none",
	dendrogram="none", trace="none", margin=c(5, 7), main="30 most highly \n expressed genes (VST)", labRow=F, key.title=NA)
invisible(dev.off())

# distances heatmap
distRL <- dist(t(rltMat))
distMat <- as.matrix(distRL)
hc <- hclust(distRL)

tiff(filename = "deseq2_distances.tiff", units="in", width=5, height=5, res=300)
heatmap.2(distMat, Rowv=as.dendrogram(hc), symm=TRUE, trace="none", col=rev(hmcol),
	margin=c(10, 6), main="Distances matrix", key.title=NA)
invisible(dev.off())

# PCA plot
tiff(filename = "deseq2_pca.tiff", units="in", width=5, height=5, res=300)
pca <- plotPCA(rlt)
pca + ggtitle("Principal Components Plot")
invisible(dev.off())

# PCA plot_labelled
require("ggrepel")
tiff(filename = "deseq2_pca_labels.tiff", units="in", width=5, height=5, res=300)
pca <- plotPCA(rlt)
pca + ggtitle("Principal Components Plot") + geom_text_repel(aes(label=colnames(rlt)),  size=2)
invisible(dev.off())

# Dispersion_plot
# plots the per-gene dispersion estimates together with the fitted
# mean-dispersion relationship
tiff(filename = "deseq2_dispersion.tiff", units="in", width=5, height=5, res=300)
plotDispEsts(dds, main="Per-gene dispersion estimates")
invisible(dev.off())

# Assign colors to the conditions
# This ensures the same colors used in the PCA are used in the heatmap for the same conditions.
# plotPCA we can't change the colors but we know that it just assigns default colors in alphabetical order
cond_colors <- hue_pal()(ll) # Get as many default ggplot colors as we have conditions
names(cond_colors) <- sort(levels) # this is a named vector where the levels (conditions) are assigned the corresponding colors by alphabetic order

#library("IHW")
# Pair-wise comparisons
#----------------------
for (i in 1:(ll-1)) {
	for (j in (i+1):ll) {
		l1 <- toString(levels[i])
		l2 <- toString(levels[j])
		conditions = c(l1, l2)
		conds = subset(sampleTable, sampleTable$condition %in% conditions)
		samples = conds$sample
		df = data.frame(condition=conds$condition)
		rownames(df) = samples
		l2l1_colors <- cond_colors[c(l2, l1)] # Will return the corresponding colors in the given order
		# in the legend (l2) will be shown first and (l1) below 
		# mimicking their positions in the FoldChange (see lines below)
		my_colour <- list(condition=l2l1_colors) # Create the input list for pheatmap
		suffix <- paste(l2, l1, sep="_vs_")
		# in results(object, contrast=c("factor", numerator, denominator))
		#res <- results(dds, contrast=c("condition", l2, l1), independentFiltering=F) # here l2 will be condition 
		res <- results(dds, contrast=c("condition", l2, l1))
		#res <- results(dds, filterFun=ihw, contrast=c("condition", l2, l1))
		#and l1 Reference
		res$FoldChange <- 2^res$log2FoldChange  
		res <- res[colnames(res)[c(1,7,2:6)]] # order columns
#		resMLE <- results(dds, contrast=c("condition", l2, l1), addMLE=TRUE)	# doesn't work
		#description <- mcols(res)$description
		# MAplot
		file <- paste("deseq2_maplot_", suffix, ".tiff", sep="")
		main <- paste("MA-plot", suffix, sep=" ")
		tiff(filename = file, units="in", width=5, height=5, res=300)
			plotMA(res, alpha= 0.05, main=main)
#		identify(res$baseMean, res$log2FoldChange)	# draw line number of gene clicking on a point
		invisible(dev.off())
		if (!is.null(orgdb)){
			symbol <- mapIds(get(orgdb), keys=row.names(res), column="SYMBOL", keytype="ENSEMBL", multiVals="first") #to obtain gene symbols
			description <- mapIds(get(orgdb), keys=row.names(res), column="GENENAME", keytype="ENSEMBL", multiVals="first") #to obtain description
			res <- cbind(symbol, res) #to add the symbols to the results file
			res$description <- description
		}
		# writing results for all & significative genes
		file <- paste("deseq2_all_", suffix, ".tsv", sep="")
		write.table (res, file=file, quote=FALSE, sep="\t", col.names=NA)
		file <- paste("deseq2_sig_padj_", suffix, ".tsv", sep="")
		sig <- subset(res, res$padj < cutoff)
		subcounts <- subset(ncounts, rownames(ncounts) %in% rownames(sig))
		subcounts <- subcounts[,rownames(df)]
		lsubcounts <- log2(subcounts+1)
		write.table (sig, file=file, quote=FALSE, sep="\t", col.names=NA)
		# save results with pvalue instead of padj
		file <- paste("deseq2_sig_pval_", suffix, ".tsv", sep="")
		sig_pval <- subset(res, res$pvalue < cutoff)
		write.table (sig_pval, file=file, quote=FALSE, sep="\t", col.names=NA)
		# heatmap of DEG
		file <- paste("deseq2_heatmap_", suffix, ".tiff", sep="")
		main <- paste("Heatmap", suffix, "log2(exp+1)", sep=" ")
		tiff(filename = file, units="in", width=5, height=5, res=300)
			pheatmap(mat=lsubcounts, color=hmcol, border_color=F, scale="row", cluster_cols=T,
				cluster_rows=T, fontsize_row=9, annotation_col=df, annotation_colors=my_colour, show_rownames=F,
				show_colnames=T, annotation_names_col=F, annotation_names_row=F, main=main)
		invisible(dev.off())
		# interactive volcano (http://sahirbhatnagar.com/manhattanly/)
		file <- paste("deseq2_volcano_", suffix, ".html", sep="")
		# collect data in a proper way
		res_noNA <- na.omit(res)
		volc <- data.frame(res_noNA$padj, res_noNA$log2FoldChange, rownames(res_noNA))
		colnames(volc) <- c("P", "EFFECTSIZE", "GENE")
		volcano <- volcanoly(volc, snp="GENE", xlab="log2FoldChange", ylab="-log10(padj)", genomewideline=-log10(cutoff), effect_size_line=FALSE, highlight_color="red")
		# save interactive plot
		htmlwidgets::saveWidget(widget=volcano, file=file, title=suffix, selfcontained=F)
	}
}

# Log file (Rastrojo's shit)
#---------------------------

sizes <- data.frame(sizeFactors(dds))
log <- cbind(sampleTable, sizes)
#log <- rbind(t(description), log)
write.table(log, file="deseq2_log.tsv", quote=FALSE, row.names=FALSE, sep = "\t")

# 5. Save work space and quit
#############################

msg1 = "!!O_o!!----------------DONE------------------"
msg2 = "That's all folks! Quitting ..."
print(msg1)
print(msg2)
save(list=ls(), file="deseq2.RData")
q()
